# -*- coding: utf-8 -*-
"""depression_file_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAzT-COl58HAMfgbuDEO-IWaha7x6FnC
"""



import pandas as pd

data=pd.read_excel('form_response1.xlsx')

data.head()

data[' Year Of Study'].unique()

data.columns

"""### replacing the values to calculate target column"""

data.replace({'Not At All':0,'Several Days':1,'More Than Half The Days':2,'Nearly Every Day':3},inplace=True)

data.head()

"""### calculating target column"""

import numpy as np

cols = [
    ' Little Interest Or Pleasure In Doing Things?',
    ' Feeling Down, Depressed, Or Hopeless?',
    ' Trouble Falling/Staying Asleep, Or Sleeping Too Much?',
    'Feeling Tired Or Having Little Energy?',
    'Poor Appetite Or Overeating?',
    ' Feeling Bad About Yourself — Or That You Are A Failure?',
    ' Trouble Concentrating On Things, Such As Reading Or Watching TV?',
    'Moving/Speaking Slowly Or Being Fidgety/Restless?',
    ' Thoughts That You Would Be Better Off Dead Or Of Hurting Yourself? (If This Bothers You, Skip This Question)'
]

data['dep_score'] = data[cols].sum(axis=1)

data.shape

data['dep_score']

import pandas as pd

data['dep_lvl'] = pd.cut(
    data['dep_score'],
    bins=[-1, 9, 14, 27],   # -1 for lower bound, 27 max PHQ-9
    labels=['Low', 'Medium', 'High']
)

data['dep_lvl']

data.iloc[52]

"""### category distribution"""

data['dep_lvl'].value_counts()

"""## extracting features we need"""

data_dep = data.iloc[:, 2:21]

"""### we work with 19 columns"""

data_dep.shape

data_dep.head()

data_dep = pd.concat([data_dep, data[['dep_lvl', 'dep_score']]], axis=1)

data_dep.shape

data_dep.head(8)

"""### finding null values"""

data_dep.isnull().sum()

"""### handeling null values"""

data_dep['Exercise Per Week'].fillna(value='No',inplace=True)

data_dep['Have You Experienced Any Major Life Event In The Past 6 Months?'].fillna(value='No',inplace=True)

data_dep.isnull().sum()

"""## removing extra spaces"""

data_dep.columns = data_dep.columns.str.strip()

"""### replacing some values"""

data_dep['Placement/Job Worries']=data_dep['Placement/Job Worries'].replace(0,'Not at all')
data_dep['Age']=data_dep['Age'].replace('25+','25-30')

"""### finding mid point from the age and sleeping hour columns"""

def age_midpoint(age_str):
    start, end = age_str.split('-')
    return (int(start) + int(end)) / 2

data_dep['Age_mid'] = data_dep['Age'].apply(age_midpoint)
print(data_dep[['Age','Age_mid']])

def sleep_midpoint(sleep_str):
    try:
        sleep_str = str(sleep_str).strip()

        if '-' in sleep_str:       # normal range
            start, end = sleep_str.split('-')
            return (float(start) + float(end)) / 2
        elif '<' in sleep_str:     # like '<5'
            return float(sleep_str.replace('<','')) - 0.5  # estimate slightly below
        elif '>' in sleep_str:     # like '>8'
            return float(sleep_str.replace('>','')) + 0.5  # estimate slightly above
        else:                       # single number
            return float(sleep_str)
    except:
        return None  # missing or invalid

# Apply to column
data_dep['Sleep_mid'] = data_dep['Sleep Hours'].apply(sleep_midpoint)

print(data_dep[['Sleep Hours','Sleep_mid']])

data_dep.columns

"""### separating X and y values"""

X=data_dep.drop(columns=['dep_lvl','dep_score','Age','Sleep Hours'])
y=data_dep['dep_lvl']

X.columns

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42,)

"""### converting data type of year of study column"""

X_train['Year Of Study'] = X_train['Year Of Study'].astype(str)
X_test['Year Of Study']  = X_test['Year Of Study'].astype(str)

X['Exercise Per Week'].value_counts()

"""### doing encoding"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

col_trans = ColumnTransformer([('ord',OrdinalEncoder(categories=[
                                                                ['Light','Manageable','Heavy','Overwhelming'],
                                                                ['Not at all','A Little','Moderate','A Lot','Extremely'],
                                                                ['Very Good','Good','Fair','Poor','Very Poor'],
                                                                ['Strongly Agree','Agree','Neutral','Disagree','Strongly Disagree'],
                                                                ['Always','Often','Sometimes','Rarely','Never'],
                                                                ['Never','Occasionally','Weekly','Daily'],
                                                                ['Never','Occasionally','Weekly','Daily'],
                                                                ['Healthy','Moderate','Unhealthy'],
                                                                ['No','Sometimes','Prefer Not To Say','Yes'],
                                                                ['Very Satisfied','Satisfied','Neutral','Dissatisfied','Very Dissatisfied'],
                                                                ['1','2','3','4','Postgrad'],
                                                                ['5+ Days','3-4 Days','1-2 Days','No']]),
                                                                ['Academic Workload','Placement/Job Worries','Sleep Quality','I Have Someone To Talk To When Stressed','I Feel Lonely','Alcohol Use','Tobacco Use','Dietary Habits', 'Have you ever experienced Panic Attacks?','How Satisfied Are You With Your Academic Performance In The Past Semester?','Year Of Study','Exercise Per Week']),
                               ('onehot',OneHotEncoder(drop='first',handle_unknown='ignore'),['Gender','Residence', 'What Helps You Cope Best?','What Coping Strategy You Use As A Student?','Have You Experienced Any Major Life Event In The Past 6 Months?'])],
                                                               remainder='passthrough')

X_train_trans=col_trans.fit_transform(X_train)
X_test_trans= col_trans.transform(X_test)



"""### using Logistic Regression"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train_trans,y_train)
y_pred=lr.predict(X_test_trans)
print("classification report\n",classification_report(y_test,y_pred))

"""### mai label encoding krna bhul gyi to logistic regression internally uso numbers m convert kr rha hai using **cat.codes**"""

print(type(y_train.iloc[0]))
print(y_train.unique())

print(y_train.cat.codes[:10])   # internal numeric codes
print(y_train[:10])

"""### using SMOTE + Logisticregression"""

from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Encode target (for SMOTE)
y_train_enc = y_train.cat.codes
y_test_enc = y_test.cat.codes

# Apply SMOTE with partial balancing
sm = SMOTE(sampling_strategy={1:70, 2:40}, random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train_trans, y_train_enc)

print("Before SMOTE:", y_train_enc.value_counts().to_dict())
print("After SMOTE:",  pd.Series(y_train_res).value_counts().to_dict())

# Train logistic regression
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train_res, y_train_res)

# Predict
y_pred = clf.predict(X_test_trans)

# Classification report with original labels
print(classification_report(y_test_enc, y_pred, target_names=y_train.cat.categories))

"""### cross validation score
###balanced_accuracy: avg of recall values
###f1_macro: avg of f1 score values
"""

from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train_res, y_train_res, cv=10,scoring='accuracy').mean()
bal_acc = cross_val_score(clf, X_train_res, y_train_res, cv=10, scoring='balanced_accuracy').mean()
f1_macro = cross_val_score(clf, X_train_res, y_train_res, cv=10, scoring='f1_macro').mean()

print("accuracy mean",scores)
print("balanced accuracy mean",bal_acc)
print("f1_macro",f1_macro)

"""### Stratified Kfolds with Logistic regression"""

from sklearn.model_selection import StratifiedKFold, cross_val_score

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

scores = cross_val_score(clf, X_train_res, y_train_res, cv=skf, scoring='accuracy')
print("Mean CV Accuracy:", scores.mean())

"""### using Random Forest"""

from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier(random_state=48,max_depth=5,n_estimators=200)
model2.fit(X_train_res, y_train_res)
#evaluating
y_pred_rand3 = model2.predict(X_test_trans)
print(classification_report(y_test_enc, y_pred_rand3))

"""### Stratifies Kfolds with Random forest"""

from sklearn.model_selection import StratifiedKFold, cross_val_score

skf = StratifiedKFold(n_splits=12, shuffle=True, random_state=42)

sc = cross_val_score(model2, X_train_res, y_train_res, cv=skf, scoring='accuracy')
bal_acc1 = cross_val_score(model2, X_train_res, y_train_res, cv=skf, scoring='balanced_accuracy').mean()
f1_macro1 = cross_val_score(model2, X_train_res, y_train_res, cv=skf, scoring='f1_macro').mean()

print("Mean CV Accuracy:", sc.mean())
print("balanced accuracy mean",bal_acc1)
print("f1_macro",f1_macro1)

"""accuracy on training data"""

train_acc = model2.score(X_train_res, y_train_res)   # training accuracy

print("Training Accuracy:", train_acc)

"""## **saving model pipline**

# creating custom transformer for changes i have done manually
"""

from sklearn.preprocessing import FunctionTransformer

def preprocess_for_predict(df):
    df = df.copy()
    if "Age" in df:
        df['Age']=df['Age'].replace('25+','25-30')
        df["Age_mid"] = df["Age"].apply(age_midpoint)
        df = df.drop(columns=["Age"])
    if "Sleep Hours" in df:
        df["Sleep_mid"] = df["Sleep Hours"].apply(sleep_midpoint)
        df = df.drop(columns=["Sleep Hours"])
    return df

# Wrap in FunctionTransformer
midpoint_step = FunctionTransformer(preprocess_for_predict, validate=False)

from sklearn.pipeline import Pipeline
pipeline = Pipeline(steps=[
    ('midpoint', midpoint_step),
    ('preprocessor', col_trans),
    ('model',model2)
])

import joblib
joblib.dump(pipeline, "depression_model2")
print("model save successfully")

"""## **creating FAST API**"""

from fastapi import FastAPI
import joblib

app = FastAPI()

# Load model once, when app starts
model = joblib.load("depression_model2")

X.columns

from pydantic import BaseModel
class InputData(BaseModel):
    Gender: int
    Year_Of_Study :str
    Residence:str
    Academic_Workload:str
    Placement_Job_Worries:str
    Sleep_Quality: str
    Exercise_Per_Week: str
    I_Have_Someone_To_Talk_To_When_Stressed: str
    I_Feel_Lonely: str
    Alcohol_Use: str
    Tobacco_Use: str
    What_Helps_You_Cope_Best: str
    What_Coping_Strategy_You_Use_As_A_Student: str
    Dietary_Habits: str
    Have_you_ever_experienced_Panic_Attacks: str
    Have_You_Experienced_Any_Major_Life_Event_In_The_Past_6_Months: str
    How_Satisfied_Are_You_With_Your_Academic_Performance_In_The_Past_Semester: str
    Age_mid: float
    Sleep_mid: float
# 4. Home route
@app.get("/")
def home():
    return {"message": "Depression prediction API is running!"}

# 5. Prediction route
@app.post("/predict")
def predict(data: InputData):
    # Request data ko dataframe me convert
    df = pd.DataFrame([data.dict()])

    #renaming columns
    df=df.rename(columns={ "year_of_study":"Year of Study",
        "Academic_Workload":"Academic Workload",
        "Placement_Job_Worries": "Placement/Job Worries",
        "Sleep_Quality": "Sleep Quality",
        "Exercise_Per_Week": "Exercise Per Week",
        "I_Have_Someone_To_Talk_To_When_Stressed": "I Have Someone To Talk To When Stressed",
        "I_Feel_Lonely": "I Feel Lonely",
        "Alcohol_Use": "Alcohol Use",
        "Tobacco_Use": "Tobacco Use",
        "What_Helps_You_Cope_Best": "What Helps You Cope Best?",
        "What_Coping_Strategy_You_Use_As_A_Student": "What Coping Strategy You Use As A Student?",
        "Dietary_Habits": "Dietary Habits",
        "Have_you_ever_experienced_Panic_Attacks": "Have you ever experienced Panic Attacks?",
        "Have_You_Experienced_Any_Major_Life_Event_In_The_Past_6_Months": "Have You Experienced Any Major Life Event In The Past 6 Months?",
        "How_Satisfied_Are_You_With_Your_Academic_Performance_In_The_Past_Semester": "How Satisfied Are You With Your Academic Performance In The Past Semester"
    })
    # Model se prediction
    prediction = model.predict(df)[0]

    return {"prediction": int(prediction)}

